name: build and test

on: [workflow_dispatch, push] 

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: mvn compile test-compile
        
      - name: Print the input name to STDOUT
        run: echo The username is Christina
